# Generated by Django 2.0.1 on 2018-01-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retrotransposons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField(unique=True)),
                ('swScore', models.IntegerField()),
                ('milliDiv', models.IntegerField()),
                ('milliDel', models.IntegerField()),
                ('milliIns', models.IntegerField()),
                ('genoName', models.CharField(max_length=120)),
                ('genoStart', models.IntegerField()),
                ('genoEnd', models.IntegerField()),
                ('genoLeft', models.IntegerField()),
                ('strand', models.CharField(max_length=1)),
                ('repName', models.CharField(max_length=120)),
                ('repClass', models.CharField(max_length=120)),
                ('repFamily', models.CharField(max_length=120)),
                ('repStart', models.IntegerField()),
                ('repEnd', models.IntegerField()),
                ('repLeft', models.IntegerField()),
            ],
        ),
    ]
