# Generated by Django 2.0.1 on 2018-01-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrotransposons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retrotransposons',
            name='unique_id',
        ),
    ]
