# Generated by Django 2.0.1 on 2018-01-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrotransposons', '0002_remove_retrotransposons_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrotransposons',
            name='unique_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
